- systemd/system/README.md
- systemd/system/flpprototype-readout.service.j2
- systemd/system/flpprototype-readout@.service.j2
Jinja2 templates for Systemd units (default and parametrized) for FLP prototype readout.
To be used with Ansible.
> Systemd readout units

- Makefile
`make` does not necessarily use non-POSIX shells
> Fix go get shell expansion

- occ/CMakeLists.txt
On my Mac, but not on the test machine, I get an error when building (see at the bottom). 
I think that there is actually an error. Boost::program_options is not header only and thus it requires to be linked against the library. What puzzles me is how it can work in most cases. Maybe I am missing something ? 
```
DEBUG:Control-OCCPlugin:Control-OCCPlugin:0: [ 42%] Linking CXX shared library lib/libOcc.dylib
DEBUG:Control-OCCPlugin:Control-OCCPlugin:0: Undefined symbols for architecture x86_64:
DEBUG:Control-OCCPlugin:Control-OCCPlugin:0:   "boost::program_options::options_description::add_options()", referenced from:
DEBUG:Control-OCCPlugin:Control-OCCPlugin:0:       OccInstance::ProgramOptions() in OccInstance.cxx.o
DEBUG:Control-OCCPlugin:Control-OCCPlugin:0: …
```
> Fix missing link to boost program_options

- core/environment/manager.go
Issue caused by task misconfiguration. In AliECS we now make sure that if a task transitions to ERROR immediately after deployment, and the environment deployment fails, we clean up afterwards.
> [core] Cleanup on failed deployment

- coconut/cmd/configuration_import.go
- coconut/configuration/configuration.go
- hacking/settings-mac.yaml
Add 'no-versioning' option to `coconut configuration import` command.
Cases to treat:
* Using `no-versioning`:
* Entry specified already exists and contains timestamps => Return error and inform users
* 
* With versioning:
* Entry specified already exists and contains no-versioning items => Return error and inform users`
> WIP [OCTRL-209] Add no-version to configuration import

- .github/workflows/control.yml
- go.mod
Add a simple basic GH Action which should run on 2 different OS and 2 different GO versions:
* OS:
* macos
* ubuntu 18.04
* GO: 
* 1.12
* 1.13
Checks:
* make vendor
* make
TBD:
* Mandatory passing of checks on each PRs to be enabled from settings
* Example of failure: https://github.com/AliceO2Group/Control/pull/110/checks?check_run_id=577277935
> [OGUI-225] add basic gh action

- occ/occlib/OccServer.cxx
- occ/occlib/RuntimeControlledObject.cxx
- occ/occlib/RuntimeControlledObject.h
- occ/occlib/RuntimeControlledObjectPrivate.h
- occ/occlib/examples/dummy-process/CMakeLists.txt
- occ/occlib/examples/dummy-process/main.cxx
> WIP: [OCTRL-295] Fill configuration ptree from local file

- occ/occlib/OccServer.cxx
(run number is unsigned long, not long long)
> Fix compiler warning about incorrect format string

- core/environment/manager.go
This is proving to be a must. Due to the fact that `onEnd` is being called no matter what (even if stream failed or succeeded), currently there is no way for me to tell when the `NewAutoEnv` has been successful unless I specifically look for the message `teardown complete` which I believe is not recommended.
I would recommend to have for this release an ending state such as the ones proposed by Teo. 
I used the `DONE` state as per the `state.go` enum file which contains the possible states of a task.
Please feel free to change it to something else if environments do not use the same convention
> [OCTRL-388] Add a state "done" for completed auto env

- core/environment/transition_configure.go
- core/workflow/iteratorrole.go
- core/workflow/role.go
Tested using standalone deployment.
The procedure was:
1) `coconut environment create -w readout-dataflow -e '{"hosts":["test-flp3"],"dd_enabled": "true","qcdd_enabled": "true","modulepath":"nil"}'` forcing wrong variable so that the deployment will fail
2) coconut will respond with `FATAL create:      command finished with error error=rpc error: code = DeadlineExceeded desc = context deadline exceeded`
3) After a few seconds `mesos` will inform the core about the tasks with state `TASK_FAILED` and `REASON_COMMAND_EXECUTOR_FAILED`
4) `transition_configure` will exit immediately with `workflow deployment failed`
5) clean up of the remaining tasks will start immediately
Resolves OCTRL-373
> [core] Transition configure should return immediately after failure in deployment

- executor/executable/controllabletask.go
- executor/executable/pid_util.go
- executor/executorcmd/client.go
I stumbled onto this almost by accident while debugging the Kill code path for other reasons, and I suspect it really *might* fix OCTRL-401 (but I'm not sure at all, testing needed).
If my assumption is correct, I suspect the problem was that the PID used by the Kill code depends on `GetState`, and prior to this fix a failed `GetState` could result in a negative PID, which was always treated as "process not running" by the `pidExists` check. Even if this doesn't fix OCTRL-401, I think it addresses a real problem.
@miltalex I know this is assigned to you and `IN PROGRESS`, I decided to just push my fix attempt here anyway because I couldn't find a branch on your end.
> Improvements to executor controllabletask.Kill

- coconut/control/control.go
- core/environment/manager.go
The first one was noticed after executing `coconut environment create -w readout-dataflow -e '{"hosts":["test-flp3"],"modulepath":"/no/path/here/"}'`, the environment deployment was failing tasks were killed but `mesos` and `roster` were reporting leftover tasks.
The second is a fix for when a failing deployment is happening if `core` receives a `SIGINT` signal during the `TeardownEnvironment` operation, it will fail with `panic close nil channel`.
> [core] Fix teardown and failed deployment issues

- core/task/manager.go
When I patched the `v0.20.5`, I was removing every `ACTIVE` task on the roster instead of the ones that we supposed to kill.
> [core] Fix empty roster issue

- core/environment/manager.go
- core/task/channel/outbound.go
- core/task/task.go
- core/task/tasks.go
@miltalex this is https://alice.its.cern.ch/jira/browse/OCTRL-395
Currently the error message about a bad channel is pushed to InfoLogger, but the environment creation still ends with `code = Internal desc = cannot get newly created environment: no environment with id 2QoHfsQU9cB`.
This is not very nice, when an env creation fails in a non-recoverable fashion we should push the meaningful error message to the user.
I've followed the call stack up to `manager.go:789`, and apparently the returned `err` is pushed to the `internalEventCh`. I did not further investigate how to forward this event up to `server.go` and return it in response to the env create call. @miltalex since you're the expert on asynchronous `task.Manager` operation, could you please look into this and conclude OCTRL-395? …
> [core] Report a channel mismatch error on bad channel configuration

- core/repos/repo.go
- core/repos/repomanager.go
* Allow addition of repos even when they don't point to the global default revision (OCTRL-499)
* Make sure that existing repos are refreshed on core startup (OCTRL-502)
> Improve repository addition

- apricot/doc/apricot.md
- apricot/doc/apricot_http_service.md
The documentation explains how to use the Apricot TCE, which is an HTTP service providing read-only information on FLPs.
> [apricot] Documentation for the Apricot TCE

- occ/plugin/OccFMQCommon.cxx
fix for [O2-2755](https://alice.its.cern.ch/jira/browse/O2-2755) with OCClite plugin. However, I have not been able to verify where the `SIGTERM` comes from and, given a graceful termination restored, whether this is enough to no longer trigger it.
Anyhow, with this change, I could gracefully shut down a test FairMQ device (`fairmq-bsampler`) with both OCC and OCClite plugins loaded and both with an `END` transition (sent via a locally modified `peanut` program) as well as with a `SIGTERM` from `IDLE` state.
> OCClite plugin: Release device control with the same plugin name as it was taken

- .github/workflows/control.yml
This reverts commit ac685b80b916ddb7cb99e04fe20802ad3dead8d2.
Since we moved to a different `kafka` package which does not contain C inside, we should be able to enable the mac build again.
> Enable the mac build again

- core/integration/kafka/plugin.go
This does not seem to have an influence on what is actually used, but perhaps this is used to report the endpoint to some other parties.
> [core] kafkaBroker -> kafkaEndpoint

- core/integration/dcs/dcsutil.go
- core/integration/dcs/plugin.go
This currently only applies to the `ddl_list` entry within the DCS SOR payload variable, so the following vars are affected:
* `dcs_sor_parameters`
* `<det>_dcs_sor_parameters` where `<det>` is the lowercase 3LA of a detector, e.g. `mid`, `phs`, `tof`.
Within this context, if the SOR parameters payload for a given detector has a `ddl_list` entry with value `default` (string), the value is instead filled out with the content of the variable `<det>_default_ddl_list` (e.g. `mft_default_ddl_list`) if such a variable exists. Otherwise, the string `default` is kept and a warning is pushed to InfoLogger.
Any `eor_parameters` variables are unaffected.
> [core] DCS override "ddl_list: default" with <detector>_default_ddl_list

- core/integration/kafka/plugin.go
It is replaced by a more precise name 'PublishEnterStateUpdate'. The old one is not used in ControlWorkflows for a few months.
> [core] Kafka: Remove the deprecated PublishUpdate callback

- configuration/componentcfg/query.go
- configuration/template/dplutil.go
If the config file address was put at the end of JIT command, as below:
```
o2-qc --config json://path/to/payload
```
then the regex would include a newline character in the matched string,
which would not pass `inputFullRegex` when building a query. However,
we would try to retrieve the configuration anyway, because there was no
error check after invoking `NewQuery`.
> [OCTRL-710][core] do not include newline char in JIT config queries

- configuration/template/dplutil.go
- configuration/template/stack.go
Now we report any problems in JIT as errors instead of smuggling them as workflow file names, which were treated as such, thus trying to open files consisting of error messages.
> [core] Improve reporting errors during JIT template translation

- executor/executable/controllabletask.go
- occ/occlib/OccServer.cxx
Could not test every possible scenario, but it seems to be fine.
> [executor] do not try to recover a task in error, ask to exit instead

- core/workflow/roleutils.go
This fixes error messages with missing failed roles:
```
cannot create new environment: transition canceled with error: workflow deployment failed, aborting and cleaning up [failed roles: ]
```
Here it is with the fix:
```
cannot create new environment: transition canceled with error: workflow deployment failed, aborting and cleaning up [failed roles: readout-dataflow.host-piotr-ostack3.data-distribution-dpl.dpl.internal-dpl-injected-dummy-sink]
```
> [core] LeafWalk should also walk in include roles

- executor/executable/controllabletask.go
- executor/executable/hooktask.go
- executor/executable/task.go
- executor/executorutil/executorutil.go
- executor/handlers.go
This truncates the long DPL commands to leave the part after the last pipe, which is the most crucial to understand what is running. We attempt to print the full command in "launching task" log. Also, the PR removes "cmd" field in logs where it is empty anyway.
> [executor] truncate task command in logs when it will be cut

- core/task/manager.go
Sometimes this is the only message from aliecs to know which task failed. It is easy to miss when it is Info. It would be even better if it had partition id included, but did not find a way to retrieve it, it is not there even in Labels.
> [core] 'task inactive exception' should be an error log

- configuration/template/dplutil.go
- configuration/template/stack.go
Here is an example of how they could be used: https://github.com/AliceO2Group/ControlWorkflows/pull/533/files
I hope that `HostnameWithin` reduces 150 string comparisons and `and` operations into a few for each FLP. In principle, we could even compare raw strings with IDs without converting them, assuming they use leading zeros, but I am not sure I want to risk it.
> [OCTRL-704][core] template helpers for assigning JIT workflows per groups of FLPs

- core/integration/ccdb/plugin.go
this works, but i am waiting on a decision in OCTRL-709 if we should accept only production FLPs or any FLPs. If the first, then the FLP prefix could be perhaps retrieved from some central value in consul or a header with constants at least...
> [OCTRL-709][core] pass flp id list to ccdb grp object

- occ/plugin/OccLiteServer.cxx
- occ/plugin/litestructs/JsonMessage.cxx
- occ/plugin/litestructs/Transition.cxx
info becomes detail, which should be translated to IL's debug, but in contrast to FairLogger's debug, it should appear in Release builds.
Needs https://github.com/AliceO2Group/AliceO2/pull/10615
> [QC-902] tune OCC log levels

- executor/executable/controllabletask.go
Since we aim to transition from ERROR to DONE, we cannot stop the loop when we reach ERROR. KILL_TRANSITION_TIMEOUT should protect us from being stuck in ERROR forever (in case we fail to get to DONE).
> [OCTRL-683][executor] ERROR should not be the last state

- core/environment/environment.go
- core/environment/manager.go
If we set run end time upon leaving RUNNING into ERROR, the trigger end time is later than run end time. CTP & PDP set a requirement that trigger end time is always before run end time.
> [OCTRL-770][core] set run end time after trg end time

- core/task/channel/inbound.go
This makes FairMQ produce an error when failing to bind a port instead of selecting a random one in the range 22000-23000, which is useless in our case.
Probably not related to OCTRL-773, but should fix O2-2818, where we obliviously run a QC proxy which could not bind a port due to a leftover task on the same machine.
> [O2-2818][core] Disable autoBind in FairMQ

- occ/plugin/OccFMQCommon.cxx
- occ/plugin/OccLiteServer.cxx
- occ/plugin/OccPluginServer.cxx
https://alice.its.cern.ch/jira/browse/O2-4340
> Try to make plugin unsubscribe from FairMQ at right time

- common/logger/infologger/directhook.go
The already existing infrastructure can map logrus' TraceLevel to InfoLogger's Debug severity and Trace level. Also, Trace logs are enabled only if the core is ran with --veryVerbose, however, they are not propagated to InfoLogger. This commit enables the propagation of Trace logs to InfoLogger. I expect the impact to be minimal, as we run with --veryVerbose only when really needed and mostly in development setups. It is not aimed to be the default mode to operate with.
This commit should have no effect on the logs from executor, as it is always ran with Debug level.
> Enable trace logs when core is run with --veryVerbose

- core/task/manager.go
This makes DONE roles (e.g. killed with SIGTERM) correctly report through mesos that they are DONE. This commit does _not_ make the environment state go to ERROR if the task off-the-rails is critical, it will be done as a part of the same ticket, but different commit.
> [core] OCTRL-846 report done roles to the task manager

- core/workflow/safestate.go
As far as I understand, this was an attempt at fixing the cases when ERROR state is overriden by MIXED, which was fixed in https://github.com/AliceO2Group/Control/pull/535 and https://github.com/AliceO2Group/Control/pull/536 directly in the state arithmetics code. I don't think this is needed anymore and happy tests seem to confirm it.
> [core] remove obsolete workaround to make ERROR state always win

- core/environment/transition_configure.go
- core/environment/transition_reset.go
- core/environment/transition_startactivity.go
- core/environment/transition_stopactivity.go
- core/workflow/roleutils.go
This does not solve the case when the task is in ERROR, but alive, but it is already an improvement.
> OCTRL-851 [core] do not attempt to transition inactive tasks

- common/event/writer.go
- core/core.go
- core/the/eventwriter.go
This is probably not the best way how to fix the issue of creating kafka writers every time we want to send the message. But I am using it as a draft to demonstrate the fix in the ticket. We will discuss with @knopers8 whether this is the best way to fix this.
> [core] keeping created kafka writers in global object

- core/environment/environment.go
While searching for the cause of [OCTRL-882](https://its.cern.ch/jira/browse/OCTRL-882) I found this error with missing mutex around channel write. It is in the middle of all the symptoms (more in the ticket), so it even might be the cause of the issue, but I cannot be sure about that without more information when the aliecs gets stuck.
As I cannot be sure that this PR will fix mentioned bug, I propose to keep this PR not merged until we will be able to demonstrate the issue with somebody being able to `delve` into the aliecs status while it gets stuck and get stack trace of all of goroutines.
> [core] Added missing mutex around eventStream in environment

- core/task/scheduler.go
which is perfectly expected situation.
> [core] inform, not warn if there is one executor on a node

- occ/plugin/OccLiteServer.cxx
FairMQ considers ERROR state as a final state and expects any plugins to exit in such case. This is of course in contradiction to our concept of the ERROR state, which we envisage to RECOVER from. This being said, since FairMQ tries to exit anyway in such cases and we do not plan to work on recovery soon, I think the best is to respect the current status quo. This fixes OCTRL-888, allowing the DPL tasks to exit upon seeing an exception and propagating it to FairMQ.
> OCTRL-888 [occ] If we see FairMQ's ERROR state, we should exit

- core/environment/environment.go
- core/server.go
- core/workflow/callrole.go
- core/workflow/taskrole.go
A bunch of easy improvements to better know why an environment goes into error:
- whenever a task goes to error, it is logged
- whenever we create a new error transition, we log what led us to it
> OCTRL-893 [core] always log why the environment goes into ERROR

- docs/handbook/operation_order.md
I think we are at the stage where things have settled down and there is a finite number of changes expected to such a document (namely: removing BKP and Kafka plugins calls, possibly moving CCDB plugin calls). One could even consider filling the hooks automatically, based on the information parsed from `readout-dataflow.yaml`, but I would leave that for later.
The reason for this document is also a request from users to know what are SOSOR, EOSOR, SOEOR, EOEOR timestamps exactly.
> OCTRL-901 Document the order of actions performed during SOR and EOR

- common/utils/utils.go
- core/integration/odc/handlers.go
- core/server.go
- core/serverutil.go
> [core] Limit ODC error string length

- core/task/manager.go
- core/task/scheduler.go
- core/task/schedulerstate.go
[OCTRL-777](https://its.cern.ch/jira/browse/OCTRL-777)
This commit addresses an issue with timing between a Mesos REVIVE call and its corresponding OFFERS event.
Specifically:
* The channel that pipes incoming deployment requests into the OFFERS handler is now buffered.
* We retry an unsatisfiable task deployment 3 times before giving up.
* The deployment request is now passed as a pointer.
* The response from the OFFERS handler to task.Manager.acquireTasks now goes through its own channel, one per request.
* The deployment request is now enqueued immediately *before* a REVIVE, as opposed to after, in order to prevent a race with Mesos.
> [core] Improve handling of Mesos resource offers

- core/environment/transition_startactivity.go
- docs/handbook/configuration.md
pdp_beam_type and pdp_override_run_start_time are propagated to tasks during SOR, so during SYNTHETIC runs they can know the right beam type and start of run correlated with the timing of synthetic data.
> [core] OCTRL-891 propagate pdp_beam_type and pdp sor override to tasks

- core/environment/environment.go
- core/environment/hooks_test.go
- core/environment/manager.go
- core/integration/testplugin/plugin.go
- docs/handbook/operation_order.md
I still want to test it with TRG plugin enabled, but otherwise, it seems already OK.
> [core] Set run timestamps before executing triggers with weight 0

- core/integration/ccdb/plugin.go
Ruben and Chiara need the O2 run duration in GRP ECS objects to be the narrowest timespan which includes CTP start and stop. Also start of run time should be ready available when the tasks are started. Because of these two reasons, we should use SOSOR and EOEOR as the timestamps in GRP ECS object.
> OCTRL-899 [core] use SOSOR and EOEOR as run duration for GRP ECS object

- cmd/o2-aliecs-core/main.go
- cmd/o2-aliecs-executor/main.go
- cmd/o2-apricot/main.go
- common/logger/infologger/directhook.go
- core/config.go
I had to change how directhook is created, because when it is triggered from `init()` it just uses default values all the time and it isn't settable.  So I moved it from `init()` to `main()` after config is being loaded and parsed.
> added logging filters for IL

- core/environment/environment.go
- core/environment/manager.go
Tested on staging with a few different cases when tasks go to ERROR, the protection works and there are no deadlocks.
> [core] OCTRL-911 Transitions should not be performed concurrently

- core/environment/manager.go
This is a fix to avoid running a second teardown attempt after a successful one. This could have happened if the 2nd teardown request was received while the 1st teardown attempt would be still ongoing. In principle https://github.com/AliceO2Group/Control/pull/600 was already enough to avoid concurrency issues and I could not make the core misbehave with it, but this commit attempts to make the behaviour somewhat more correct.
I hesitated to set the state as DONE if `TeardownEnvironment` returns earlier with an error, since this does not remove given environment from the manager's list of enviroments, thus technically it is still available for more teardown attempts. On another hand, this contradicts the already published kafka events, which advertize the env state as DONE even when it …
> [core] OCTRL-911 do not teardown an environment in DONE

- core/environment/environment.go
- core/environment/hooks_test.go
- core/environment/manager.go
- core/workflow/callable/call.go
This addressed the problem of having stuck calls waiting for something to receive from c.await which outlive the parent environments. This may happen if awaited trigger never occurs after it has been started, e.g. if trigger is before_START_ACTIVITY and await is after_START_ACTIVITY, but the environments fails to transition to RUNNING.
> [core] OCTRL-912 Cancel calls pending await upon environment destruction

- core/environment/environment.go
- core/environment/manager.go
- core/task/manager.go
The three commits fix what was observed as wrong while investigating the case with env `2pedNJwSjL8`. The updated core was confirmed to work correctly in this test scenario.
> OCTRL-920 Fixes for stuck calibration runs 

- core/task/scheduler.go
- core/task/schedulerstate.go
sorry for some of the formatting fixes.
There was a race condition which was in method `makeTaskForMesosResources` where we sharing `global` object to write. This should create a deep copy of given object and it seems to fix the problem on staging.
> QC-779  Multiple mesos executor fix

- core/integration/dcs/plugin.go
The reason for this is described in ticket [OCTRL-924](https://its.cern.ch/jira/browse/OCTRL-924)
> removing kafka event in DCS plugin for EOF received from DCS

- core/integration/dcs/plugin.go
Added kafka message to DCS for any detector change for any detector
> [OCTRL-928] Add kafka event for DCS SOR state SOR_PROGRESSING

- core/task/manager.go
- core/task/scheduler.go
- core/task/schedulerstate.go
I found why multiple mesos REVIVE commands can be issued. Sorry for the clutter in PR, but it is just automatic formater.  The idea was to add `reviveOffersDone` channel to be used instead of `reviveOffersTrg` for sending acknowledgement when REVIVE call was done. 
I am not saying that it fixes OCTRL-777, just the issue of multiple REVIVE calls in one short time that we discussed Tuesday.
> use two channels to communicate mesos REVIVE

- core/task/manager.go
- core/task/scheduler.go
- core/task/schedulerstate.go
This reverts commit e99d4195bb234bc0c7c2d078b5ff6a684d9012dd.
Reason being that I made a mistake. Channel in golang without size is blocking by default, I thought that it is not. So the thing that I thought can happen really can't. Sorry about that.
> Revert "use two channel to communicate mesos REVIVE"

- core/environment/transition_deploy.go
- core/task/manager.go
- core/task/scheduler.go
I talked with Vasco and it is possible to release and deploy before HI if we do just log changes. So I went over logs from OCTRL-777 logs and moved these to Devel level so crew will not get overwhelmed when this error (which is covered by retry) is triggered.
For the record: this PR is not meant to be as a whole solution for OCTRL-945, I am still working on more concise logging.
> moved logs connected to unknown undeployable to Devel

- core/environment/manager.go
[core] removed wrong code in environment/manager.go TasksStateChangedEvent
> OCTRL-954 Core got stuck while tearing down environment 2qzDsSFXRL8

- occ/occlib/OccServer.cxx
- occ/occlib/RuntimeControlledObject.h
There is no point in asking the controlled task for a health check if it's still in ERROR. The task can go to healthy state by requesting a recover transition, which gives a success or failure as a return value.
OCTRL-958
Tested on staging, it seems to behave as expected and I do not see any unexpected side-effects.
> [occ] do not call iterateCheck when in ERROR

- configuration/template/stack.go
- core/integration/odc/plugin.go
https://its.cern.ch/jira/browse/OCTRL-974
> Ensure the detectors variable is sorted where possible

- Makefile
- common/ecsmetrics/metric.go
- common/ecsmetrics/metrics.go
- common/monitoring/metric.go
- common/monitoring/monitoring.go
- common/monitoring/monitoring_test.go
- core/config.go
- core/core.go
This PR is adding http endpoint to be scraped by other tools (eg. Telegraf). Apart from mechanism to create metrics endpoint I also added mechanism to publish [golang internal metrics](https://pkg.go.dev/runtime/metrics).
P.S.: I changed this to a draft, so we can discuss it before merging.
> [core] Adding http metrics endpoint

- configuration/template/stackutil.go
- core/environment/transition_deploy.go
- core/task/manager.go
- core/workflow/taskrole.go
- executor/executable/controllabletask.go
See commit descriptions for details.
> Several log improvements

- docs/handbook/operation_order.md
According to the change in https://github.com/AliceO2Group/ControlWorkflows/pull/670
> Update operation_order.md with trg.RunStop change

- common/ecsmetrics/metrics.go
- common/monitoring/monitoring.go
- common/monitoring/monitoring_test.go
- core/config.go
- core/core.go
Fixed race condition which results in golang metrics reporting being stuck by adding check to monitoring.Send function. Other refactoring and documentation
> [core] fixing and refactoring monitoring

- core/controlcommands/commandqueue.go
- core/controlcommands/mesoscommandservent.go
- core/task/manager.go
- core/task/task.go
- "task '/opt/o2/bin/o2-readout-exe' on alio2-cr1-mvs11 (id 2sBwA3Z8yWU, name alio2-cr1-hv-gw01.cern.ch:/opt/git/ControlWorkflows/tasks/readout@12b11ac4bb652e1835e3e94806a688c951691d5f#2sBwA3Z8yWU) failed with error..." displayed by COG becomes "task 'readout' on alio2-cr1-mvs11 (id 2sBwA3Z8yWU) failed with error...". I believe the removed information is not useful for typical operators. Details can be always found in logs.
- "MesosCommand MesosCommand_Transition timed out for task 2sBwYFZ82wn" becomes "MesosCommand_Transition timed out for task 2sBwYFZ82wn" because by convention, all MesosCommands have "MesosCommand" in their names.
- If a transition request times out, more accurate error is reported in COG. "nil response" becomes "CONFIGURE could not complete for critical tasks, errors: …
> [core] improved error reporting during env deployment/configuration

- core/integration/odc/plugin.go
> [core] propagate pdp_beam_type as FairMQ property to ODC tasks

- Makefile
- common/utils/utils.go
- core/environment/environment.go
- core/environment/manager.go
- core/environment/transition_startactivity.go
- core/environment/transition_stopactivity.go
- core/integration/odc/plugin.go
- executor/executable/basictaskcommon.go
- executor/executable/controllabletask.go
A bunch of OPS logs was moved to SUPPORT or DEVEL, while some of the OPS logs were made simpler.
OCTRL-978
> [core][executor] fine-tuning operator logs

- common/event/writer.go
- added key to messages containing environment id or run number
- changed Balancer from LeastBytes to Hash which makes kafka-go puts messages with same key to the same partition, fixing ordering problems
I did not add any tests, because I was unsure how to test this properly, so I just tested this on my openstack machine.
> [OCTRL-985] Place kafka messages related to same environments in the same partition

- common/event/writer.go
use task ID for task message instead of environment for `Ev_TaskEvent`.
> [OCTRL-990]: Place kafka events related to the same task in the same partition

- core/integration/odc/handlers.go
- core/integration/odc/plugin.go
- docs/handbook/configuration.md
OCTRL-987
This involved extracting `setProperties` as a separate helper to share it between `Start` and `Stop`, and adding it to `Stop`, which was not the case. Contrarily to `Start`, we do not abandon `odc.Stop` in case `setProperties` fails, so we still have an attempt to stop the run.
Tested on staging, it looks like `setProperties` takes 50ms when using 2 EPNs. Looking at the past logs in production, it usually takes no more than 100ms, so I don't think anyone should complain, while this lets us use correct EOR time in QC.
> [core] ODC: Send SOR/EOR timestamps as FMQ properties

- core/server.go
https://its.cern.ch/jira/browse/OCTRL-992
> [core] Ensure doNewEnvironmentAsync gets its own copy of args

- apricot/local/service_test.go
- core/integration/dcs/dcsutil.go
It's a small bug, which required the users to use a variable `TOF_dcs_send_enabled_links` instead of `tof_dcs_send_enabled_links` to enable the feature brought in OCTRL-980. Now we require lower-case detector code.
OCTRL-994
> [core] sending enabled links to DCS should require a lower-case var

- common/protos/events.proto
- core/environment/environment.go
- core/environment/manager.go
- core/task/task.go
- removed `vars` from Ev_RunEvent
- changing status and state of Task in kafka message only if event contains them
- properly filling `traits` in Ev_TaskEvent from task.Traits
> [core] OCTRL-989

- o2-aliecs-shmcleaner
Now, we have a patch in PDA which makes the deep cleanup unneeded.
> Disable ROC deep cleanu procedure

- occ/CMakeLists.txt
Since the new abseil in https://github.com/alisw/alidist/pull/5793 appears to expose c++20 in headers, we have to bump accordingly.
> [occ] bump OCC to c++20

- core/integration/dcs/plugin.go
This changes how we consume reply streams of requests to DCS. In particular, we do not stop consuming events in case we receive a detector error and instead we wait to receive the status of all the other detectors.
As it has been clarified with the DCS team, Ecs2DcsGateway never sends "a pre-closure summary of the current operation" with `detector == DCS`, despite the documentation in the dcs.proto file. The latest version of this proto file in the Ecs2DcsGateway repo has the comment removed.
With this commit, we treat an EOF from DCS as the only correct stream termination and do not ever expect a `detector == DCS` event.
We also remove some reduntant operations, but more refactoring will have to come.
Closes OCTRL-711.
> [core] ECS waits until DCS operation completes in case a detector fails

- docs/handbook/operation_order.md
As done in https://github.com/AliceO2Group/Control/commit/56e07f5ff8db060cfe7c6b499f5eec02d27f6732 , PFR continues for PFR-compatible detectors, even if some are incompatible.
> [doc] Update DCS PFR documentation

- core/integration/dcs/dcsutil.go
In this case, the mechanism was replaced with the outcomes of OCTRL-980, so we do not need ddl_list to be defaultable anymore.
Closes OCTRL-995.
> [core] Remove ddl_list from defaultable values in DCS plugin

- core/task/task.go
Fixes a bug reported in OCTRL-999.
The recursive locking happens in the following trace:
```
5  0x000000000122c829 in github.com/AliceO2Group/Control/core/task.(*Task).GetParent
at /home/alibuild/sw/BUILD/eb488922a0fabb8512ec137d3a765b22d2941067/Control-Core/go/src/github.com/AliceO2Group/Control/core/task/task.go:741
6  0x000000000122597c in github.com/AliceO2Group/Control/core/task.(*Task).GetTraits
at /home/alibuild/sw/BUILD/eb488922a0fabb8512ec137d3a765b22d2941067/Control-Core/go/src/github.com/AliceO2Group/Control/core/task/task.go:248
7  0x000000000122a217 in github.com/AliceO2Group/Control/core/task.(*Task).SendEvent
at /home/alibuild/sw/BUILD/eb488922a0fabb8512ec137d3a765b22d2941067/Control-Core/go/src/github.com/AliceO2Group/Control/core/task/task.go:528
```
> [core] fix a recursive mutex locking in task

- common/event/writer.go
There was a goroutine in `WriteEventWithTimestamp` which can cause race condition resulting in problems mentioned in ticket OCTRL-998. 
However, there can be performance problems caused by removing this concurrence, as every Kafka write call will wait until the message is send by the writer. This can be prevented by setting writer into async mode. But doing so we won't get any errors that might happen while sending messages. From kafka-go/writer.go Async comment:
```
// Setting this flag to true causes the WriteMessages method to never block.
// It also means that errors are ignored since the caller will not receive
// the returned value. Use this only if you don't care about guarantees of
// whether the messages were written to kafka.
```
> [OCTRL-998]: Sending kafka messages in wrong order

- common/ecsmetrics/metric.go
- common/ecsmetrics/metrics_test.go
- common/event/event_suite_test.go
- common/event/fifobuffer.go
- common/event/fifobuffer_test.go
- common/event/writer.go
- common/event/writer_test.go
- common/monitoring/monitoring.go
More details about this KafkaWriter rewrite are in writer.go notes
> [OCTRL-1001]: Levarage kafka-go writer's ability to send messages in batches

- core/server.go
This swaps Error and Message in two kafka events which deviated from the general convention, where Message contains a general, hard-coded string explaining a moment/step that an environment was at, while Error contains the specific error. It was agreed with George and this allow COG to look for "cannot create new environment" and "cannot get newly created environment" message to report the global error of an environment creation failure.
> [core] put error in the Error field of events

- core/integration/bookkeeping/plugin.go
int32 to string() conversion takes the bytes literally, one should use strconv library instead. Fixes OCTRL-1014.
> [core] fix malformatted fill_info_fill_number passed to controlled tasks

- core/environment/environment.go
- core/environment/transition_startactivity.go
I moved resetting of currentRunNumber from `StartActivityTransition` object if some tasks fail to start to `GO_ERROR` transition after message of EOEOR is send.
@knopers8 Do you think that this can break something? Or do you propose something else?
> [OCTRL-1016]:  Missing runNumber in KafkaEvent on topic aliecs.run

- common/event/writer.go
- common/event/writer_test.go
this is follow up on OCTRL-1003 with changes to kafka which I used to test metrics on STG and openstack. Just small tuneup of kafka-go producer, so it does not take 1s to send batch of messages which is incomplete (not 100 messages).
This branch is based on OCTRL-1003 (to distinguish metrics changes and kafka changes) so that one should be merged first to see real changes just in writer.go and writer_test.go
> Kafka adjustments

- core/controlcommands/commandqueue.go
This log cannot be understood by an operator on its own.
typically, there is another error log just after, which includes this message, but also gives some context:
```
transition 'START_ACTIVITY' failed, transitioning into ERROR. error="transition canceled with error: START could not complete for critical tasks, errors: task 'source /etc/profile.d/o2.sh && export DPL_RAWPROXY_OVERRIDE_ORBITRESET=1718863780392 && o2-qc --config apricot://alio2-cr1-hv-aliecs.cern.ch:32188/o2/components/qc/ANY/any/tof-full-epn-qcmn --remote --shm-metadata-msg-size 100000 -b | o2-qc' on alio2-cr1-qc03 (id 2uWFxUQq3ku) failed with error: MesosCommand_Transition timed out for task 2uWFxUQq3ku"
```
i think it's fine to move it to Devel
> demote MesosCommand send error log

- core/integration/dcs/plugin.go
When ECS2DCS2ECS is used as the DCS server, one can specify expected reply to requests by adding "STATE_SEQUENCE" to request extra parameters with a key formatted as below:
```
MILLIS_DELAY:DETECTOR_STATE[,MILLIS_DELAY:DETECTOR_STATE]*
```
This commit exposes a possibility to set these sequences via configuration parameters. Essentially, this allows us to have some configurations on staging which use DCS with pre-defined state sequences.
> OCTRL-1026 [core] allow to specify a test state sequence upon DCS requests

- go.mod
- go.sum
This fixes `make generate`, which fails due to the issue discussed in https://github.com/dmarkham/enumer/issues/105
> [build] bump enumer to fix generation with go 1.24

- README.md
- core/integration/README.md
> [doc] document ECS2DCS2ECS mock server usage

- common/monitoring/monitoring_test.go
The monitoring tests include some pseudo-random outputs which sporadically go out of originally expected, too narrow margins, which is perfectly normal. The commit extends the margins.
> More permissive margins in monitoring tests

- occ/CMakeLists.txt
It does not work and it's in any case obsolete.
> Avoid specifying the FairMQ version

- core/environment/manager.go
Probably due to a mostly harmless mistake, we would force an environment into ERROR state even when not needed, after a successful GO_ERROR. If very unlucky, this could cause some conflicts with following transitions towards environment destruction.
This affects only GO_ERROR due to ODC going to ERROR, other cases are fine.
I did not see this bug cause any troubles, I just accidentally stumbled upon it.
> No need to force ERROR when GO_ERROR succeeded

- core/integration/odc/plugin.go
This allows us to stop a run on EPNs at GO_ERROR transition by adding a corresponding ODC.EnsureStop hook.
As GO_ERROR can occur with any source state, we make sure to make the actual STOP call only if the ODC partition is in RUNNING.
At the same time, ODC partitions require us to call ODC.Stop if they voluntarily transition to ERROR.
In such case, ODC.Stop allows the remaining healthy devices to finish processing.
By keeping the original ODC.Stop behaviour, we preserve this functionality.
Additionally, the commit includes minor corrections to a few related logs.
Fixes OCTRL-1036.
> Call ODC STOP only when the partition is in RUNNING

- core/server.go
This becomes consistent with two other events in this function, which report failure to create an environment.
> Add a message for the event reporting successful environment creation
