README.md

If you wish, there is no obligation.

Add a shield for JIRA tickets (JADMIN-291)

---

core/scheduler.go

This is necessary because the executor links against InfoLoggerForGo, which in turn requires `LD_LIBRARY_PATH` to point to the libdir of aliBuild/RPM-based GCC-Toolchain.
When deploying Mesos agents, every agent's `MESOS_ATTRIBUTES` must contain a string entry named `executor_env_LD_LIBRARY_PATH` which points to the latest GCC-Toolchain/lib64 found during deployment time (done via Ansible). This attribute is then made available with each Mesos offer, and the AliECS-core scheduler component must include it in the `Environment` of the `CommandInfo` of the `ExecutorInfo` to be launched.
See `control-node` role in `system-configuration/ansible`.

Acquire LD_LIBRARY_PATH from Mesos Agent attribute and push to executor

---

occ/CMakeLists.txt

Those changes fixed my [building issues](https://cernbox.cern.ch/index.php/s/oJOBo7Kuur5tf9m) on MacOS (Mojave, SIP enabled)

[QC-200] Fixes for macos

---

core/environment/manager.go
core/environment/transition_configure.go
core/scheduler.go
executor/executor.go

Increase deployment timeout
Release tasks on failed env creation
Do not go into global error state on task failure
Improve log output

Miscellaneous fixes

---

core/config.go
core/confsys/service.go
core/core.go
core/scheduler.go

* Create a single writable directory path. 
* Persistent Mesos Framework ID.
* Store Mesos Framework ID to Consul under `o2/aliecs` or to a local file under `/var/lib/o2/aliecs`.
* Create reconciliation call on every re-registration.
* Kill tasks received from reconciliation.
Close OCTRL-170

[core]:Persistent FID

---

common/utils/utils.go
core/config.go
core/confsys/service.go
hacking/config.yaml

[core]: repos and runcounter.txt are stored inside coreWorkingDir

---

core/core.go
core/signals.go

[core]:Handle Unix Signals

---

core/config.go
core/confsys/service.go
core/repos/repo.go
core/repos/repomanager.go
core/task/manager.go
hacking/settings.yaml

[core]: remove repositoriesPath from configuration

---

coconut/cmd/repo_default_revision.go
coconut/control/control.go

[coconut] Fix repo default-revision bug & improve documentation

---

core/scheduler.go
core/workflow/taskrole.go

[core]: fix segfault for unsatisfied constraint or resource

---

executor/executable/controllabletask.go

[executor] Prevent endless loop in ERROR state

---

core/repos/repomanager.go

[core] Fix getWorkflowTemplates bug

---

core/workflow/template/fields.go
core/workflow/template/stack.go

[core] Add type conversion functions to template system

---

configuration/consulsource.go

Ensure o2/control/run_number exists in Consul.

---

core/task/task.go

task_name
task_id
task_class_name
task_hostname
environment_id
task_parent_role

[core] Push special variables to task.BuildTaskCommand

---

core/server.go
core/task/channel/inbound.go
core/task/channel/outbound.go
core/task/class.go
core/task/descriptor.go
core/task/match.go
core/task/task.go
core/workflow/parentadapter.go
core/workflow/role.go
core/workflow/rolebase.go
core/workflow/taskrole.go

Allow templating and overriding of channel configuration

---

core/task/class.go

[core] remove target for outbound channels in task template

---

executor/executor.go

[executor] Set memlock limit to unlimited for child processes

---

coconut/protos/o2control.pb.go
core/protos/coreevents.go
core/protos/o2control.pb.go
core/protos/o2control.proto
core/scheduler.go
core/server.go
core/state.go

WIP: Event stream support

---

core/repos/repomanager.go

[core] Change warnings about repo access to debug

---

configuration/componentcfg/componentcfg.go
core/confsys/service.go
core/task/task.go
core/workflow/template/stack.go
occ/occlib/OccServer.cxx
occ/plugin/OccFMQCommon.cxx
occ/util/Common.h

Ptree push support 

---

core/scheduler.go

[core] Set periodic output severity to Trace

---

executor/executable/controllabletask.go
executor/handlers.go

Related to OCTRL-263 and OCTRL-262

[executor] Concurrent Kill and SIGTERM

---

walnut/cmd/convert.go
walnut/cmd/root.go
walnut/converter/converter.go

[walnut] Allow selection of output directory

---

executor/executor.go

[executor] Handle HEARTBEAT event

---

core/scheduler.go
core/server.go
core/state.go
executor/executable/controllabletask.go

Fix deadlock in core

---

walnut/schemata/validate.go

[walnut] verbose validation errors

---

coconut/cmd/root.go
coconut/control/control.go
common/controlmode/controlmode.go
common/taskcmdinfo.go
core/controlcommands/mesoscommand_triggerhook.go
core/controlcommands/mesoscommandservent.go
core/environment/environment.go
core/environment/manager.go
core/scheduler.go
core/server.go
core/task/manager.go
core/task/task.go
core/workflow/aggregator.go
core/workflow/role.go
core/workflow/taskrole.go
executor/executable/basictask.go
executor/executable/basictaskcommon.go
executor/executable/hooktask.go
executor/executable/task.go
executor/executor.go
executor/executorcmd/transitioner/transitioner.go
executor/handlers.go

Support for Hooks

---

core/workflow/taskrole.go
walnut/schemata/Workflow.json

[walnut] add support for hook task specification

---

walnut/schemata/Workflow.json

[walnut] change range subfields to string

---

core/workflow/load.go
core/workflow/rolebase.go

[walnut] omit empty fields during marshaling

---

core/workflow/graft.go
core/workflow/load.go
walnut/cmd/convert.go
walnut/converter/converter_test.go
walnut/converter/dump.yaml
walnut/converter/small.yaml

[walnut] add support for workflow grafting

---

core/workflow/rolebase.go
walnut/schemata/Workflow.json

[walnut] add support for enabled flag

---

coconut/control/control.go
common/utils/utils.go
core/workflow/load.go
core/workflow/rolebase.go
walnut/cmd/convert.go
walnut/converter/converter.go
walnut/converter/converter_test.go
walnut/converter/testvalues.go

[walnut] variabilize commonly useful vars

---

core/workflow/graft.go
walnut/cmd/convert.go
walnut/converter/converter_test.go
walnut/converter/small.yaml

[walnut] graft role as child of specified role

---

core/workflow/load.go
core/workflow/taskrole.go
walnut/cmd/convert.go
walnut/converter/converter.go
walnut/converter/converter_test.go

[walnut] move defaults from WFT to TT

---

.github/workflows/control.yml

Updated go version to be in line with current supported versions
Updated action `checkout` to v2 and `go` to v2 as they bring performance improvements and bug fixes

Update Go Version

---

coconut/control/control.go
common/utils/uid/uid.go
core/environment/environment.go
core/environment/manager.go
core/scheduler.go
core/server.go
core/task/errors.go
core/task/manager.go
core/task/task.go
core/workflow/parentadapter.go
core/workflow/role.go
core/workflow/rolebase.go
core/workflow/template/stack.go
go.mod
go.sum

If this works well, it should probably also be used for task and other IDs.

Use sony/sonyflake via indigo for short environment IDs

---

core/task/task.go

[core] Push environment_id as property to all tasks

---

core/environment/transition_configure.go

[core] Always get the stateChanged after a transition

---

core/environment/environment.go
core/environment/manager.go
core/environment/transition_configure.go
executor/executable/controllabletask.go
executor/executorcmd/client.go
executor/executorcmd/nopb/test/main.go
occ/peanut/peanut.go

Handle workflow error state

---

core/integration/ddsched/plugin.go

This is necessary to make DD calls blocking

DD scheduler polling for CONFIGURED/TERMINATED partition state

---

core/bookkeeping/api.go
core/bookkeeping/utils.go
core/config.go
core/environment/environment.go
core/environment/transition_startactivity.go
core/environment/transition_stopactivity.go
core/the/singleton.go
go.mod
go.sum

Bookkeeping Integration

---

coconut/cmd/repo_add.go
coconut/cmd/repo_default.go
coconut/cmd/repo_default_revision.go
coconut/cmd/repo_refresh.go
coconut/cmd/repo_remove.go
coconut/control/control.go

Add coconut docs for repo commands

---

coconut/cmd/repo.go
coconut/cmd/repo_add.go
core/config.go
core/repos/httpsrepo.go
core/repos/httpsrepo_test.go
core/repos/localrepo.go
core/repos/localrepo_test.go
core/repos/repo.go
core/repos/repo_test.go
core/repos/repomanager.go
core/repos/sshrepo.go
core/repos/sshrepo_test.go
core/server.go
core/task/manager.go
core/task/match.go
core/workflow/aggregatorrole.go
core/workflow/callrole.go
core/workflow/includerole.go
core/workflow/iteratorrole.go
core/workflow/load.go
core/workflow/role.go
core/workflow/taskrole.go

Addresses OCTRL-296 and OCTRL-514.

[repos] Extend support for ssh & local backends

---

core/bookkeeping/api.go

[core] Bookkeeping bypass jwtToken

---

core/controlcommands/commandqueue.go
core/controlcommands/mesoscommandservent.go
core/environment/transition_deploy.go
core/task/constraint/attributes.go
core/task/scheduler.go
core/workflow/aggregatorrole.go
core/workflow/callrole.go
core/workflow/safestatus.go
core/workflow/taskrole.go
executor/executorcmd/client.go
executor/handlers.go

These are the changes to reduce the verbosity of the 30 logging messages generating the largest Infologger traffic.

Reduce logging verbosity

---

apricot/local/service.go
apricot/protos/apricot.proto
apricot/remote/server.go
apricot/remote/service.go
configuration/service.go
core/server.go

[apricot] Add getAll flag for ListDetectors RPC

---

core/task/manager.go
core/workflow/load.go

* The first step is to implement this feature for the workflow, and in a second step, to implement it for the tasks.

[OCTRL-203] Check identifiers on task and workflow loading

---

core/integration/kafka/plugin.go

[core] Kafka: more logs, require ACK from all brokers

---

core/task/task.go

This reverts commit 3eabd9f3a23637dcaf74dfb26fd498b4117999a7.

Revert "[task] Add a random sleep of up to 10s before each task for debugging purposes"

---

core/integration/bookkeeping/api.go
core/integration/bookkeeping/plugin.go
go.mod
go.sum

PR which:
* updates the call `UpdateRun` done via the Bookkeeping Plugin to send more fields to Bookkeeping:
* pdp_workflow_parameters
* pdp_beam_type
* readout_cfg_uri
PR is based on @claireguyot work but split in 2 PRs as it cannot be tested in one go. Original PR: https://github.com/AliceO2Group/Control/pull/414

[OCTRL-702] Add more fields to Bookkeeping Plugin

---

core/integration/dcs/protos/dcs.proto

NOISE runType, [SOR|EOR]_UNAVAILABLE detectorState

DCS proto file updated

---

core/integration/odc/plugin.go

Ticket here: [OCTRL-736](https://alice.its.cern.ch/jira/browse/OCTRL-736)

[core] Amend EPN script call generator according to OCTRL-736

---

coconut/cmd/environment_show.go
coconut/control/control.go
coconut/control/controlutil.go
core/config.go
core/workflow/aggregatorrole.go
core/workflow/iteratorrole.go
core/workflow/load.go
go.mod
go.sum

Credit goes to Kostas and @claireguyot for rounds of prototyping and testing.

[core][OCTRL-583] Bring back optional concurrency in workflow processing

---

core/integration/odc/plugin.go

[core] add FLP ID list and deployment type to the ODC script

---

core/integration/kafka/plugin.go

[core] Prevent crash in Kafka plugin concurrent map access

---

core/integration/odc/plugin.go

[core] Add pdp_epn_shm_sizes param to ODC plugin

---

core/server.go

[core] Enable RPC call logging in non-verbose operation

---

common/event/integratedserviceevent.go
core/environment/manager.go
core/integration/odc/event/odcevent.go
core/integration/odc/plugin.go

If ODC goes to ERROR during RUNNING, AliECS stops the env into CONFIGURED.

Handle spontaneous ODC ERROR transition

---

configuration/template/dplutil.go

This commit makes the JIT template generation support both consul-json and apricot backends of the O2 Configuration library. Also, instead of the LastIndex, we use the processed configuration payload in the hash sum which is used to detect any relevant changes in the DPL workflows.

[core] hash processed config payloads from apricot during JIT

---

core/environment/manager.go

[core] Improve auto-transitioning environment events to GUI

---

core/workflow/callrole.go
core/workflow/role_test.go
core/workflow/roleutils.go
core/workflow/safestate_test.go
core/workflow/taskrole.go
core/workflow/workflow_test.go

More details in the description of specific commits.

Never propagate non-critical task state to parent, add tests

---

core/workflow/callable/call.go

https://its.cern.ch/jira/browse/OCTRL-898

[core] Push CallEvents to aliecs.call topic

---

occ/plugin/litestructs/Transition.cxx

https://its.cern.ch/jira/browse/OCTRL-895

[occ] Fix deserialization of ConfigEntry with empty value

---

configuration/template/dplutil.go

As experienced by Uli last night, there was no indication in the message seen in the ECS GUI about which particular workflow failed and which detector does it belong to. This adds this information and removes DPL command output from that message and sends it to Infologger (saying it can be found there).

[core] log the failed JIT workflow and detector, push DPL out only to IL

---

core/environment/manager.go

@graduta FYI
https://its.cern.ch/jira/browse/OCTRL-903

[core] Set state to DONE in last autoEnv event - stopgap until Kafka switch

---

Makefile
core/integration/plugin.go
core/integration/plugin_test.go
core/integration/testplugin/plugin.go

...building towards a test for hooks

test the plugin system

---

core/environment/environment.go

https://its.cern.ch/jira/browse/OCTRL-908
@martinboulais FYI

[core] Publish correct state when tasks_<TRANSITION> is done

---

executor/executor.go

See:
https://its.cern.ch/jira/browse/OCTRL-766 @sy-c 
https://its.cern.ch/jira/browse/OCTRL-769 @Barthelemy

[executor] Chmod sandbox directory 750→755 so task can read it

---

core/integration/ddsched/plugin.go

https://its.cern.ch/jira/browse/OCTRL-914
https://its.cern.ch/jira/browse/EPN-482

Make StfB/StfS-to-FLP maps local for each request

---

core/integration/dcs/plugin.go

Added missing kafka messages to DCS for SOR and EOR

Missing kafka messages for OCTRL-927 and OCTRL-928

---

core/task/manager.go

Fixes nil access issue introduced by myself in https://github.com/AliceO2Group/Control/pull/647

[core] fix nil task access

---

core/workflow/safestate.go
core/workflow/safestatus.go

document what is safe about SafeStatus and SafeState

---

.gitignore
Makefile

I just added a check whether we are in alidist environment (by checking env variable PROTOBUF_VERSION)

OCTRL-1035 Use one version of protoc

---

core/environment/environment.go

Simplify critical hook execution error targeted towards operators
